/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/companyinfo
 */
export interface CompanyInfo {
  Id: string;
  SyncToken?: string;
  CompanyName?: string;
  CompanyAddr?: {
    Id: string;
    PostalCode?: string;
    City?: string;
    Country?: string;
    Line5?: string;
    Line4?: string;
    Line3?: string;
    Line2?: string;
    Line1?: string;
    Lat?: string;
    Long?: string;
    CountrySubDivisionCode?: string;
  };
  LegalAddr?: {
    Id: string;
    PostalCode?: string;
    City?: string;
    Country?: string;
    Line5?: string;
    Line4?: string;
    Line3?: string;
    Line2?: string;
    Line1?: string;
    Lat?: string;
    Long?: string;
    CountrySubDivisionCode?: string;
  };
  SupportedLanguages?: string;
  Country?: string;
  Email?: {
    Address?: string;
  };
  WebAddr?: {
    URI?: string;
  };
  NameValue?: {
    Name?: string;
    Value?: string;
  }[];
  FiscalYearStartMonth?: string;
  CustomerCommunicationAddr?: {
    Id: string;
    PostalCode?: string;
    City?: string;
    Country?: string;
    Line5?: string;
    Line4?: string;
    Line3?: string;
    Line2?: string;
    Line1?: string;
    Lat?: string;
    Long?: string;
    CountrySubDivisionCode?: string;
  };
  PrimaryPhone?: {
    FreeFormNumber?: string;
  };
  LegalName?: string;
  MetaData?: {
    CreateTime?: string;
    LastUpdatedTime?: string;
  };
  CompanyStartDate?: string;
  domain?: string;
  sparse?: boolean;
}
